steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}:${_TAG_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}:${_TAG_NAME}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - '${_DEPLOYMENT_NAME}'
  - '${_CONTAINER_NAME}=gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}:${_TAG_NAME}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_PROJECT_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_PROJECT_CLUSTER}'
substitutions:
    _CONTAINER_NAME: petsrego
    _TAG_NAME: latest
    _DEPLOYMENT_NAME: petsrego
    _PROJECT_ZONE: us-central1-a
    _PROJECT_CLUSTER: petsrego-cluster
options:
    substitution_option: 'ALLOW_LOOSE'