apiVersion: v1
kind: Service
metadata:
  name: petsrego
  labels:
    app: petsrego
spec:
  selector:
    app: petsrego
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer